name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Display greeting
        run: echo "Hello World!"
      - name: Display goodbye
        run: echo "Done bye!"
